import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>importedgallo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>importedgallo</a> homepage
        </h1>

        <p className={styles.description}>
          A site by {' '}
          <code className={styles.code}>Andre Mongard</code>
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>About Me &rarr;</h2>
            <p>Find out more about my hobbies, background.</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Resume &rarr;</h2>
            <p>Education, work experience, core competencies.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Projects &rarr;</h2>
            <p>View my projects and upcoming projects.</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Contact Me &rarr;</h2>
            <p>Contact email, LinkedIn, and Github.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        Built with Typescript, Next.js, Chakra-UI
      </footer>
    </div>
  )
}

export default Home
